export const LOGIN_ACTION_TYPE = {
    LOGIN: 'USER_LOGIN',
    LOGOUT: 'USER_LOGOUT'
}
export const ORDER_ACTION_TYPE = {
    ADD_ORDER: 'ADD_ORDER',
    CLEAR_ORDER: 'CLEAR_ORDER',
}

export const MENU_ACTION_TYPE = {
    ADD_FB_MENU: 'ADD_FB_MENU',
}